unlock internet_osi_optimized;
unlock internet_osi_transfer_rate_optimized;
unlock internet_osi_rate_optimized;
unlock internet_osi_protocol_optimized;
unlock internet_osi_rate = 10gb/s;
unlock internet_osi_rate = 10gbps;
unlock internet_osi_rate = unlimitedbyte;
unlock internet_osi_rate = unlimitedbit;
unlock internet_osi_transfer_rate = unlimitedbit;
unlock internet_osi_transfer_rate = unlimitedbyte;
unlock internet_osi_connection = unlimitedconnection;
unlock internet_osi_protocol = unlimitedprotocol;
unlock internet_osi = unlimitedosi;
unlock internet_osi = unlimitedinternetosi;
unlock internet_osi_connection_rate_optimized;
unlock internet_osi_connection_rate = unlimitedconnectionrate;
unlock internet_osi_virtual_rate = unlimitedvirtualrate;
unlock internet_osi_virtual_memory = unlimitedvirtualmemory;
unlock internet_osi_load = unlimitedload;
unlock internet_osi_performance = unlimitedperformance;
unlock internet_osi_html = unlimitedhtml;
unlock internet_osi_bandwidth = unlimitedbandwidth;
unlock internet_osi_rostelecom = unlimitedrostelecom;
unlock internet_osi_rate_size = unlimitedratesize;
unlock internet_osi_rate_size = unlimitedbyte;
unlock internet_osi_rate_size = unlimitedbit;
unlock internet_osi_transfer_rate_size = unlimitedbit;
unlock internet_osi_transfer_rate_size = unlimitedbyte;
